name: Update GitHub Stats

on:
  schedule:
    - cron: "0 */6 * * *"  # Обновлять каждые 6 часов
  workflow_dispatch:  # Позволяет запускать вручную

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Update README with GitHub Stats
        run: |
          echo '<p><img align="left" src="https://github-readme-stats.vercel.app/api/top-langs?username=exttreme0001&show_icons=true&locale=en&layout=compact&count_private=true&token=${{ secrets.GH_STATS_TOKEN }}" alt="exttreme0001" /></p>' > README.md

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add README.md
          git commit -m "Update README with latest stats" || echo "No changes to commit"
          git push
